INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('djibouti', 'Djibouti', NULL, NULL, 'https://w3id.org/okn/i/mint/Djibouti');
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cC3OtoP3aeYpGeU1baaJ', 'Ali Sabieh', 'djibouti', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Sq1qOveQBZCdJrLikpBN', 'Dikhil', 'djibouti', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7NvEhXtGD7i4myJVKSK5', 'Djibouti', 'djibouti', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Hae2WW2Mlw3ERgIvgcyp', 'Obock', 'djibouti', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5fWMrs35ZA5ApW40GOWR', 'Tadjourah', 'djibouti', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('1vt5OvjgoRRBfagdbOvv', 'Ali Sabieh', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7SS6BfUbKtfuVJwBXm8x', 'As Eyla', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Hxqa1QN7wZrRMNBEd80H', 'Dikhil', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nv1aXCDSJJBn8g1DuR9U', 'Yoboki', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4rinqF8TvfzucYLx2w7b', 'Djibouti', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9EvTmnjmNfnGN0xrMOEj', 'Alaili Dadda', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('L0d4f1uG8P4cxYK1KwA0', 'Obock', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('X19ZGrbha7J0noRPQ9Ki', 'Balha', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Rqoh7cEmDbQqvW2yDQ9F', 'Dorra', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3kkyxVPQ1oxLj38fYM3y', 'Randa', 'djibouti', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OKlY34Nxcu0uF9LbQ8iJ', 'Tadjourah', 'djibouti', 'administrative_level_2', NULL);
