INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rbWiLlYhRCMrdWBPmkBw', 'Kongur', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('S1T6Hpd7MF5nDWYPAmwn', 'Aeiud', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0Vogrk1MgfhUBDWYq4ot', 'Bor', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rmTQX5Q1PzLcQgfCcpjH', 'Fenjak', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lvbzPhyLNqvtpo6iIxXw', 'Akoba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rnmtpRHeutB5c9DiTf2J', 'Bashola', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pMRsrRDdQq5dB3AtjcDL', 'Bybor', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rytkl70BrIefcui8mFyu', 'Wat', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AbhuZk717pO69VO8IGPr', 'Oeiryal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4VRi5HcSqMD5P0DVTRMa', 'Rumbeik', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lkrfUAnOGiVqou9TYaDS', 'Shaweit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('608tMEyme7OJF0boeD6X', 'Yerol', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5gfOMcv2NfsdSvdY3DCB', 'Odeth', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pFEP6aL4MdRsBqEMO0eM', 'Aweil', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O3Di032vRKA1oPvkBvVB', 'Rurali', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dcDi1Na7y4gJ2HeMJK8v', 'Wanjak', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9WS46liyDPlbeMzf6W68', 'El Leiri', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TkyYIHuY4khyH3MwRc4w', 'El Meidom', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bRgWe06yXSye2j1VJ1me', 'Unknown_1', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pzWKRBIrkPJ2GO1UlSmH', 'Bentiu', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Ts9IkD61KIuSA43FTTyf', 'Mabein', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OPRgx0o2JWFqKnSLO9lw', 'Rank', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O4QebFBFYvRyRIgB8b3m', 'Baleit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8YWeUFIOCrWj7HOtRLxC', 'Kodok', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OfGcncjZfHu0gtZdwWIw', 'Malut', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HAgcibttlG1pgSw3O0Z5', 'Mayot', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jqVzebwrtaPhPUi3gpAI', 'Naser', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bsBfFyQb1FsJDa3ot3Us', 'Malakal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Z46l3jh96RvFHadOfShc', 'Gogiryal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7RnHqEdd2ythisAJsWqV', 'Unknown_2', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7oL4ERlFy5uMyjIPaAev', 'Teite', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jbzDfkjfexEDVWeY5vUg', 'Warab', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rrTS9TpfjAv7jMzyJIvQ', 'Raga', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hcJh3r1mqFDHwKzJGUpM', 'Wau', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ssHbQZ7DLerAZ0090eQj', 'Eiba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('shd7f3Jhi2ut1q5j0Oov', 'Mareidi', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gBOevyOiDV3sSeXCJsr2', 'Mendry', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wNzL5BFVOCysYbmgIiIO', 'Ezura', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('NIqh4sUHvJJPHVgzc9aP', 'Tombura', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qD9Ov8cesb2S4W4JPI4X', 'Yambio', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('south_sudan', 'South Sudan', NULL, NULL, 'https://w3id.org/okn/i/mint/South_Sudan');
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('v2Ma3NAJpsu7AwI6JDBW', 'Central Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J7XlLJtDrpdq6xh9z94X', 'Eastern Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jZl8S5JHJvNdIwTJOKEY', 'Jungoli', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pYi3hTJYWcgQJru8BnaN', 'Lakes', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xcn2yPkcp750MMZNH5Kr', 'North Bahr-al-Ghazal', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Hiua10aB82T7zYhvryeh', 'Unity', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qw1VGk5hEah3qqLUtanz', 'Upper Nile', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9smOAf2rZnJNEM5zeiSx', 'Warap', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oFmWLW1OnXxCujbEzN13', 'West Bahr-al-Ghazal', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aXXgxnzeeqp37ZzDVROT', 'West Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kjjcQjpUmTwgl6TA9STU', 'Bahr al Jabal', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fY7IN4CfTsNvDtjv0rJ8', 'Kajo Kaii', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EhkHCvGJxMtHctX6q7KH', 'Nahr Yei', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('1TrmOwSnlk2wgMwwAzvL', 'Terkaka', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dK0RkoTk5zRAMuOXaYwa', 'Amatonge', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PfKJQ5XFXH7rqGXZ8Sew', 'Kapoeta', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('i4igQuyb9Dg1gaew1JC9', 'Magwi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kv37sIVoDnFn5ODumMHd', 'Shokodom', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DwaCPOlsDe26dklOoVcU', 'Akobo', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qKmk97t0BQrN54SFEt9o', 'Ayod', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hUSXx8jkELJN9ENoNCAT', 'Bor', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dOZcASTFGZnNppfT8UdP', 'Fam al Zaraf', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2P7ygNiJC44BsDTrPZys', 'Nahr Atiem', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('us2BK9YYdudc0FJeb6PR', 'Pibor', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J5xa2MeC23aLGhACqrSr', 'Wat', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vpocai9CN1QjimesP809', 'Aliab', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nwP3wwMFM8I6BS15uhwo', 'Rumbek', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('19ooffLj1tKtP8sI8CsL', 'Shobet', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('35mfdozC9fC166DIcMXi', 'Yerol', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('G8nasE86UrSgQELppIa1', 'Aryat', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ATPmTFNAyfqlfQONMvHQ', 'Aweil', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ht3CGUKgxJ8kHHM7CHKj', 'Nahr Lol', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Vz63wpKlfgz90gNOnYZf', 'Wanjuk', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jQIaJreGjMka2D8M9mQ0', 'Al Leiri', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('g0NNVqbAIBHZND4igRzV', 'Al Mayom', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9VLDOMhuFy7uYUOpX3JL', 'Faring', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vw6KlV4r8939RZv8ra0j', 'Rabkona', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('R6tJoXDxPMaOgi34x0QR', 'Al Mabien', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iqGRayxCNElLdNHgpX48', 'Al Renk', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oR1CsLUD4QeX24rpaoBN', 'Baleit', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WQej9EvL82shtcKJS375', 'Fashooda', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('YxEbipNo8q2CdTbOdcvG', 'Malut', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8bJFKrgr55NyoOEdl8mi', 'Mayot', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TeVYd2NqpA9lNwr7n44S', 'Sobat', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VxCn4lLxd5w245CMIDQq', 'Tonga', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kzNYhYGjWfA0lN6paxjp', 'Gogrial', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('i34AKx1wEmk9H4Fb80cb', 'Malek', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QsDTAiPeFo4JjrwFn5QQ', 'Tonj', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J4EyVTB9FlwYR1JkiZqk', 'Warab', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4jnR9CEWddKtbWP5oaaV', 'Raja', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mt3iUzNTexK3mHAW3Un6', 'Wau', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zy9oQnO5bIWihkHgX26T', 'Meridi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6iUqKLPX4n68GxQ1VEWS', 'Mundri', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fqsaG0UFSDvMprivtsuH', 'Tombura', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('y9JTJf0bBW2Yp3ngClfV', 'Yambio', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J2iuXWUkDHAbjspnUhwQ', 'Juba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O03JKmGJb7wpoUsBYfWf', 'Kajikaji', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EjfvkxBUnX7fkUAveQTx', 'Yei', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XGqtSssZuqMGQ0jyl7AO', 'Treikaka', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uIQhEB4OLf6ACXpo05Z4', 'Akotous', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Trhw2bHWdcsZLOLXc4td', 'Toreit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4stbyWzPljNrnFY0ngry', 'Kaboyta', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3NX9YFCjDrKWAkmrXATN', 'Magoy', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RpExVsXCHJjj3nKs62of', 'Shokodam', 'south_sudan', 'administrative_level_3', NULL);
