INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('eritrea', 'Eritrea', NULL, NULL, 'https://w3id.org/okn/i/mint/Eritrea');
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ow5RCcPWIXIscgdCnKd1', 'Anseba', 'eritrea', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('juUHgBzXMsPRHl72DXub', 'Debub', 'eritrea', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('JxshzfArOXq3RW6UaCM3', 'Debubawi Keyih Bahri', 'eritrea', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('T7tjRKGwieCwfFRbf8Y5', 'Gash Barka', 'eritrea', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fpnhs7ocvNWuwfbNijLC', 'Maekel', 'eritrea', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8CEzKQ9qSYvmQgKrE7vz', 'Semenawi Keyih Bahri', 'eritrea', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fuq3As8dL5esgKl2c4gh', 'Asmara City', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pzE4RJi425O7CRHY8d5P', 'Berikh', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9r1uQohxDiGsUmRB6Ozb', 'Ghala Nefhi', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('CeA6UVOpp4tw7il6Xfr4', 'Serejeka', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QiwHvjdX8QNZs9zEoNSC', 'Afabet', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ffp7lql59UeJ2IGleocI', 'Foro', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wTuLOERIgeOtBUyYrkOo', 'Ghelaelo''', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WbV3b3e4afYpb1ze5hP2', 'Ghida`e', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tGzkeBLlZInRBdYP8V4r', 'Karora', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('R0Pv3HG13n3YLUO4sttC', 'Mitswa`e City', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cyo0jz6UXpYzaTQdMaOX', 'Nakfa', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TzJYw1qTi5q6YFy1EU3R', 'Sheib', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EWyYD4xKYEtXCT7GjabD', 'Areta''', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DLmu4lGhq6bz1TOkgTId', 'Central So. Red-Sea', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SZrAtno6pArZuFb6ALGt', 'Dahlak', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uGA3iVwKlFSJUSWnF3uj', 'So. Southern Red-Sea', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nbfTsBsOGWIW2xB5Am0y', 'Akordat', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6NI9J14yRaDlZZpmpipW', 'Barentu', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Ae3UyysglVCXlkB5hkv8', 'Dghe', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('seiukVgzRpfimOGrRMPj', 'Forto', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BVuX1z4waEPa6klmSuQF', 'Gogne', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VJlO6JKdlCHiqK3SCgl9', 'Haykota', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cqpxzARR6dq1gIBCP56r', 'La`Elay Gash', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DA8q1pvQ4qCmOXosNAFl', 'Logo Anseba', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('54Kiw0odXVUSGOUX4xvb', 'Mansura', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VolFe6leOIBcSlY96w7y', 'Mogolo', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wyTGwQ5OQwRC8599Y9Xd', 'Omhajer', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('t484WV59cNJxFBKS8Gin', 'Shemboko', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dE9rRCgoIwiEq86eqDXC', 'Teseneye', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mcQ3eEpqozQhj4cNYwv5', 'Adi Keyih', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XSaZKYsmHQrFvc9tzniR', 'Adi Kwala', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('q9R0ZbHRF0v7GOHZCcCH', 'Areza', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qb2MimiL00pCJsitxfs0', 'Dekemehare', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('P7cfsags6E8uBDl5gMCl', 'Dibarwa', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WjCDF76MJoMA6Q7isTBO', 'Kudo Bu`er', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rjCzpgB6R99HhWVGWu8Z', 'May Mine', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0Pu2JGgWbvpystepF9tt', 'Mendefera', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nQnsEDNiaLhA93xxFU9l', 'Segeneyiti', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0uaIMRN2dSzBTeZmH5A0', 'Senafe', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XKCm65q4XiHnOEPJGF87', 'Tsorena', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('w5xkoUbRoxA9J8bQm8SH', 'Adi Teklezan', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yqLbY5omzsZxFJ7ayHT8', 'Asmat', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('V9WWMalzgFPavnKxgxh3', 'Elabered', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Z8vCeAM2OVCveGJ6q0yt', 'Gheleb', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vWOJ0ZJXxChWSTNohfxN', 'Habero', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SS7yw5umfiozQzh0M3ix', 'Hagaz', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4P1fGYzWL94Y0JFFjsjU', 'Halhal', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('g0VIgDRBCpQpqRUre5uk', 'Keren', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('e7vGmoBEYFDgB6kdiqR6', 'Kerke Bet', 'eritrea', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('e9dNIWhtvaYZFCPvO9IX', 'Sel`a', 'eritrea', 'administrative_level_2', NULL);
