INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('south_sudan', 'South Sudan', NULL, NULL, 'https://w3id.org/okn/i/mint/South_Sudan');
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sudan', 'Sudan', NULL, NULL, 'https://w3id.org/okn/i/mint/Sudan');
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('D6YKAE48sLMsBubx9UMY', 'Al Jazirah', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cI9k2KV8mYQDb4ZDF91U', 'Al Qadarif', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Chafks0Aj4rDIqntgdVD', 'Blue Nile', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Qgw8HFC3zdck3TvBxG5g', 'Central Darfur', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xAMlxuVx22tt99crezvs', 'East Darfur', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('m6THDwfq6o4xel6YaKq7', 'Kassala', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DSeyerMC9tfkLtKaRa3N', 'Khartoum', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TTNAEHPddwZdo0EB1X7l', 'North Darfur', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4ZxMuQT6xuhArGLV04cj', 'North Kurdufan', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gscFrXV7yG7XU4PTy3Z9', 'Northern', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('eZvt6KBfX2rZG3IpwSOI', 'Red Sea', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pqxR0z2rYU8lznhUwXbC', 'River Nile', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9MKIwNwRSDYIEgbj16pY', 'Sennar', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Dqg066BPYllPGACpty45', 'South Darfur', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('CKMbvCsVhJiahmyyvLul', 'South Kurdufan', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Bt87i2geMiZ5WmtzH71t', 'West Darfur', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qgBhXN8MSIZDigwHz9dq', 'West Kurdufan', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nhMBCHahxuIial3QgUmB', 'White Nile', 'sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rbWiLlYhRCMrdWBPmkBw', 'Kongur', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('S1T6Hpd7MF5nDWYPAmwn', 'Aeiud', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0Vogrk1MgfhUBDWYq4ot', 'Bor', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rmTQX5Q1PzLcQgfCcpjH', 'Fenjak', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lvbzPhyLNqvtpo6iIxXw', 'Akoba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rnmtpRHeutB5c9DiTf2J', 'Bashola', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pMRsrRDdQq5dB3AtjcDL', 'Bybor', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rytkl70BrIefcui8mFyu', 'Wat', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AbhuZk717pO69VO8IGPr', 'Oeiryal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4VRi5HcSqMD5P0DVTRMa', 'Rumbeik', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lkrfUAnOGiVqou9TYaDS', 'Shaweit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('608tMEyme7OJF0boeD6X', 'Yerol', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5gfOMcv2NfsdSvdY3DCB', 'Odeth', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pFEP6aL4MdRsBqEMO0eM', 'Aweil', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O3Di032vRKA1oPvkBvVB', 'Rurali', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dcDi1Na7y4gJ2HeMJK8v', 'Wanjak', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9WS46liyDPlbeMzf6W68', 'El Leiri', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TkyYIHuY4khyH3MwRc4w', 'El Meidom', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bRgWe06yXSye2j1VJ1me', 'Unknown_1', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pzWKRBIrkPJ2GO1UlSmH', 'Bentiu', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Ts9IkD61KIuSA43FTTyf', 'Mabein', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OPRgx0o2JWFqKnSLO9lw', 'Rank', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O4QebFBFYvRyRIgB8b3m', 'Baleit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8YWeUFIOCrWj7HOtRLxC', 'Kodok', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OfGcncjZfHu0gtZdwWIw', 'Malut', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HAgcibttlG1pgSw3O0Z5', 'Mayot', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jqVzebwrtaPhPUi3gpAI', 'Naser', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bsBfFyQb1FsJDa3ot3Us', 'Malakal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Z46l3jh96RvFHadOfShc', 'Gogiryal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7RnHqEdd2ythisAJsWqV', 'Unknown_2', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('o0Z1eoGDk8UnXwqUMp5g', 'Al Kamlin', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('x561KpgVuoNUJF6dBHSG', 'Al Mahagil', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0uoSri7BIgxKjxcRkZQN', 'East al Gazera', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tuIlCPOyyM7lj6WMoxB6', 'North al Gazera', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mpTduywSZqp23uWqD6Ag', 'Sharq al Gazera', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EfUvrYTpoG0l2CKZVNfG', 'South al Gazera', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('l11qZGTN3m4d739kIEjm', 'Um Al Gura', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('eLZ6pHn2bk9m5gwzeLRo', 'Al Faw', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6vblSadg99C2r2upkAP0', 'Al Fushqa', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VLjEhcaBQGRELopxg7Gp', 'Al Gadaref', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Bvov436z5tN7qZQ6052d', 'Al Galabat', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2uSQEUGF9qfWVxKC7AOo', 'Al Rahd', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KKnKNf7IAmc0FBi1dw3l', 'Ad Damazin', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5WxUXaH1oKvksbPFCPbg', 'Al Kurumik', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6fErmd5XuW0X2yqQ6KKv', 'Al Roseires', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XYYWAOeEzZebQsBtEzqF', 'Baw', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('I2QPL0Zxi4BOXiOkCRDk', 'Geissan', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kkZnN8KOI5gCHEaLhfhs', 'Mukjar', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qa5gMV2u6FvVYWuADCCE', 'Zallingi', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SBk2ZAR0rRxYFR5oFKtF', 'Al Deain', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EpumtzBHUPlYClMfN5NU', 'Nyala', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('padSSx2Ikc3tr7sWGBtx', 'Al Gash', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UJ47kb1L3str1CyadZrO', 'Hamashkorieb', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('JCpRm4GHPaX5P0zx5uLX', 'Kassala', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VGCPHEU0FjCldvSCtfZn', 'Nahr Atbara', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('X1Cm4YtYNMMfbAmTTf7i', 'Seteet', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Bxb6ElXbr5m6IGGXAMtI', 'Karary', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oYLqwzJkqxsSOMir08fL', 'Khartoum', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HWLHHpI3FM2J0gFczrnn', 'Khartoum Bahri', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Cla4201BhYhXBkHh5la3', 'Omdurman', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lt7zJwd7IB7XgParLKhA', 'Sharg En Nile', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('IP1V92EyrGvSoUFbbSF6', 'South Khartoum', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sr1Zf3Ny3Z8Wir7zQmlU', 'Um Badda', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('FUkIcmMfloFmLvP7WX1e', 'Al Fasher', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('YivmrnRBIKOLXEs7ZmFf', 'Kabkabiya', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BK9kvOL4cESS6N12j9N5', 'Kutum', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UVZbqeYAckOaih1ApKsU', 'Mellit', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6oAgD5adztuAxRhfmQvR', 'Um Kadada', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dhqxxbLzmsDKmFmupHMS', 'Bara', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QgKEMdHHPPSXxBhxGXyA', 'Jebrat al Sheikh', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2jFCaA98WAAESoRrkgse', 'Sheikan', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gG78Sh7YUinMMbK2roix', 'Sowdari', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('FTO9WIyNVYX39LA3LdHl', 'Um Rawaba', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7mWiw6Bm3dkCOnJIqHtH', 'Addabah', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Zd9ynC1dVHLiSr0cxk94', 'Dongola', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Y7BWjQiQ89883W8zKOr6', 'Merawi', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('GVvdxfMSV70Kw3OKnr8S', 'Wadi Halfa', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KTo6DNQLp8nsxFos1GNT', 'Halayeb', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('IEq3nI7skFQDgEpoIyPc', 'Port Sudan', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('okIqWw7sTgdvTneR1aPv', 'Sinkat', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uPqg8bFY1XUCKiUeilnF', 'Tokar', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0tvkyOkXtpbl5z3GnGtQ', 'Abu Hamad', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('G4zeDaswF3ZFvCxQywOf', 'Ad Damer', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qJwaA9eVNHU8eU6rp3OW', 'Al Matammah', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jvV0nMNgDSTWRDd55Iz6', 'Atbara', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7Y3ZcGqjsrkjrWB4TF54', 'Berber', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('FhyBu85bd8pw8Ib2ATyT', 'Shendi', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('noXQ4XZJAnNk1rz96QyN', 'Ad Dinder', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xnACsHcbuDsUG5RpBYGg', 'Sennar', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cD2qJxENUAOKdcE4paIY', 'Singa', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EQkwbkRIInthF0GCHjlS', 'Buram', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O3o8Jt4MsTQUph87Vihf', 'Id El Ghanem', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cpMfycTse3m9jh2ErvLN', 'Kas', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('c4kAShnliJjk5txqVGPh', 'Tulus', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pV4TrVsEONfINAwkWt5M', 'Abu Jubaiyah', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6pkyrDAi0fueW3D7Y8kA', 'Dilling', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SUUdtBP0d2WDCGCIs6IB', 'Kadugli', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EF2WGDLUtjrNcIJPVwx3', 'Rashad', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('LNL0B5yCGdLWhuazo2Ob', 'Talodi', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zJAKilaNXAPvLUzWCpUa', 'Al Geneina', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('1Lo5kJ7XXauhycY9aU4j', 'Abyei', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UqY0JV5NdiaOdGZnpP3J', 'As Salam', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ypmy1Bq0BUcDGihmQ7eC', 'En Nuhud', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wLnaPROUerQomQghnYy5', 'Ghebeish', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('N44Sco97sGSRXhirwdfT', 'Lagawa', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KW5KTL4cTgV1f570gtxu', 'Ad Douiem', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wVkHjh3SiSm5gHOycAfC', 'Al Gutaina', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7BubSHagh1PQ05bVDiUs', 'Al Jabalian', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('goarRJXDvL4c0I0rqO8w', 'Kosti', 'sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Cvr3BDQ8afSj1IwYSZWO', 'El Kamlin', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WUc9pDcc0Fo8MYaM20Ux', 'El Masid', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('NePyN0vnULeVgpCRtw9t', 'El Mi Eiliq', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TSvcFyywuBPfdrIrIua1', 'Es Sideira', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sG28dbxbaXmlcwBA9YMi', 'Al Azazi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MgXR6fnRdc2iWa508x6q', 'El Bura', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('s8b4UY8WO6uOluPA2qT2', 'El Huda', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4JWNNf55d2QYzOsEZVAC', 'El Kereimet', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lbJPy308BJoOklpY8Vto', 'El Qurashi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PEbfwkGZGTYhOAHQsMWc', 'El Rakha & El Matori', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vNySERuQ4v0fBTq0tfqG', 'Ma Tuq', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sz9jACkItkfYlcfVU3hK', 'Sarhan', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nQICxNsim36goG6BvwRi', 'Wad Adam', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8UFRtHXUALRChXKPB9uP', 'Abu Haraz', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('FRPrANTo6QP7FO9nbTEJ', 'Barakat', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('j6qgy8QklGAPbBwrSpzb', 'Hantub', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EYmnZrCAjM45gGPli7TN', 'Shabarga', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5BMq2D4jpG7HTLDeKf9U', 'Sharif Ya Qub', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tS5NcmRI5E0xcoiRBtSd', 'Abu Guta', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jgOaiHlPUTJe9wrfZVdh', 'El Hasaheisa', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Q1VqLSniuZ83pQLvgpwF', 'El Mesellmiya', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rF0RGXWekq8c74jD0Lur', 'Er Riba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7uv0sE9YxspNIxk2PM4v', 'Meheiriba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yYl4ymFTT1QhrxvvCRDb', 'Wad Haboba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('56035E3iy0fYqr2m2R6g', 'Eg Geneid', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KnebPvWvxzYTs2uaNO5B', 'Eidag', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('n4GnjqUk2yCB5EP6MxEO', 'Rufaa', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7dgmgLdyT9Er7blTerxs', 'Tambul', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qaC0OWbUu35FLhId4WTf', 'Abud', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4GaICTJmJttwoOAWrRsE', 'El Gamusi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oMKueMOtSEoXm49vlEY2', 'Kedeibat', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('L3eJ5cQjBtz6qzn5K7XM', 'Wad El Libeih', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('GZWpm3lSia4bjkfTtYjO', 'El Hosh', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jnVBlxeOIIAwubDfwHKY', 'El Madina Arab', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SFvOITAI19pjqtHzLdEs', 'Hag Abdalla', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EsmWiHlCZKcxgHZW0JFH', 'Tayba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UQ3G3wywhz1zPye768JD', 'Wad Al Hadad', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ycig5yOoJl99xTwqOW7k', 'Wad En Naim', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RuLqEEtu6J2ewUTdhgUs', 'Wad Raiya', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3vsxOClUy4ssRNOfvTQU', 'El Butana', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HPG8iwoaoJlvADkXMXmG', 'Shuwak', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('i4GbOWqKrHllBmsGd5ar', 'Khashm El Girba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('isBUevHaTbMkrrnGWMBX', 'Wad El Heilu', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ljg2f0ithWUCzjKii2VU', 'Unknown_3', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('luE9jiBUidp1lb0YFXTX', 'Doka', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qjg82Kx7HIpJnrJwHIJE', 'El Mogran', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('IEF6PxLDTVrVdFjdSjeD', 'Kassab', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XoZweiSpzNjgt0c9VLq8', 'Al Faw', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SNQXckhXPYghqDnRBsKa', 'El Hawat', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DQtFq2PP2xJzPUWEK98I', 'El Mafaza', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mOHe0C8tdUwABwqE9vkF', 'Qala El Nahl', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BbQsXoEitwk6PiI3QgGj', 'Ed Damazin', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('1DRlBUKoMHCqVn941tFf', 'Kurumuk', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aR7HMaTF22uQslNmS1tA', 'Ora', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('h6DvSj1VcIICLiOwwDOf', 'Er Roseires', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vBje8rlhVISIzUTz6Pg1', 'Baw', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('NXkE9uyrmw4RG0etUVb7', 'Geissan', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EJFwsXHOfTV4q9hosMxN', 'Keili', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gWPxSOOCglycalh2JtDc', 'Garseila', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KsP9YRcth6JfyAa0vFn9', 'Mukjar', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KHnSFn2NaFahy5wMKvku', 'Zamabaya', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ASkoKRGjpP6SfixMvZBl', 'Azom', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Snkm9q9b0glj5JtZMklg', 'Gulu', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J6mrwBfNC06kuS4ezsT0', 'Nertiti', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xvFhAaykS6eaB7y7UQGc', 'Rokerro', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TPdJm1BD67SNmv8T8XfM', 'Zalingei', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6s2deLnT5CyEKdzPNT3U', 'Abu Matariq', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Skka2jOGa4VlMw2TNybb', 'Adeila', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('C3wC06W2vvb9KCaubnEL', 'Ed D Aein', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WRhu98La32bJWYoeFNdd', 'Ferdous', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tJOXpGmgQMcRhaD0TUcO', 'Nyalla East', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Cylg3ZpUz4MVq6Y0KL3z', 'Aroma', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gxToeCQ1wt6TrtexVnRU', 'Genoub El Dalta', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TV1MqZiOOGOy2jDhZ2GS', 'Qoz Regeb', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lzHhDJNlV0Tibhvh89pR', 'Shmal El Dalta', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('GOxkoQrXf1FZ5cElpfj0', 'El Hudud', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('shG1yfuwb0XbtTKywy9x', 'Kassala', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('C6dpZGWNjABIqqzDNgFF', 'El Masana', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tsnrnSnuYHEuosngceMw', 'New Halfa', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Y3ZfMFDSEMOWOekI7PdV', 'Sabaat', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RGeqaj9LVfp7E0l2si28', 'Unknown1', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mBlk3H2ayIZHLmFd4nfq', 'Omdurman Shamel', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('X4PCSPRqrLhcyZz4byN5', 'Khartoum Shamel', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VxpHLCadXkqbGlqyuYDU', 'El Geili', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9n8gIg6LuUmyfqD6QfDr', 'Es Sileit', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WxgJb60yT22QDTCv4O3n', 'Khartoum North', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('P06vI8lWnA3NpbzIFBQ3', 'Omdurman Genoub', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SMHLb0aILDxFObCQEPoV', 'Abu Deleig', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0lAN17uTpq87IZAU7Nms', 'Alalafon', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EgtiSZ8Dxno0lb8RzJZm', 'Alaseilat', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DjrYh7wYC8buFmCCBhDc', 'Umm Dounban', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('GsnTdo2RaTsugZUm1G4K', 'Jebel Aulia', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HjG9qwJTb5TfEuWTNVRc', 'Omdurman Gharb', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xXvqvjphNZYtxkg4Vn6X', 'El Fashir', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tcvei7kFyaUNDu3S6zxB', 'Kattal', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('f4yGd95z45R08hy8Jqnr', 'Korma', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('s44U8FBurMsYtiWT37F3', 'Tawilah', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vpsfytYw7MvFlr2cu0eo', 'Es Serif', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lO9B9G8rGoVOoM7jkBVd', 'Kabkabiya', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ef9SpxZY3vpezdkaQD10', 'Serif Omar', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('85Dqy6CfIUHrsR2xxaBd', 'Karnoy', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TturuISv2tvNycn31cFO', 'Kottom', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UgPr8x0saZ4dyk3HG4yE', 'El Maleha', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8ATyHZl3xSjs5ZIQHno3', 'Millet', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uWZ07y2bK0syc6eSpMsM', 'Umm Barro', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RO296cuMsIoAVnKVPvel', 'El Le Aeit En Nabi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ggoV6SFozOLmuCMa41mK', 'Umm Kedada', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BVDEDcjqiG2W2WLuQHdB', 'Kazgeil', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jqhLtmaeBCTHDmrHNLwG', 'Khur Taget', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XxiaHAOtCeDhr79Sa4s0', 'Umm Ashira', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AZD8vha44tgvw3mZnGkM', 'Jebrat Esh Sheikh', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('v3zbQZKoZ7np9J0Ml2Zy', 'Bara', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EEd38ucxQMpR144i4KqD', 'El Mazroub', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4EMxSLT5VVcoqWkAOy6c', 'Greigikh', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2lVsqlMRRx6x4ChU5ARi', 'Umm Gerfa', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WUmuQXQ9pmkCDpwAwJMu', 'Umm Kereidim', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Js8BqW3yM1S1jJUUPFlY', 'Umm Sayala', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('V76qKLjAFhKun1b9mZ9g', 'Hamrat El Wiz', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('x78Lv0Ll7bz0OnfPbHGn', 'Hamrat Esh Sheikh', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('eGjFNOe5I6AmtKlfqVmp', 'Sawdari', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('L3KFA7rbz1GwhcKu2ifi', 'Umm Bader', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xD4qUgs89I1JDpJlwmA5', 'Er Rahad', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('20uKdOJAlNMhlTGWMePE', 'Shirkeila', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3GCJZ1SeH6d1sHXpXmIb', 'Umm Dam', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MatSy1YOSvswXcTDHW4L', 'Umm Rawaba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OfCU6RRbDqUj1o9IaTYi', 'Wad Ashana', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MMQyUSCnachUABjQO0Vq', 'Ed Dabba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Vv32YiZRgn3IeFjZjPWA', 'Argo', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BIanVV96CDrwN3uHtsRz', 'Dongola', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VS5tzQL1U9Iz1RY7cPRT', 'El Golid', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AQyRaF6VvvHlx41IQkWS', 'Karima', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aBV7492JrELCz7aLvFwm', 'Marawi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('R1C4Lw2gd12Uf1Jd51TW', 'Abri', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7DIXwbeQaEj4Pd34GWqF', 'Delgo', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lGbwTbRYpq6jjeKesz50', 'Wadi Halfa', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('V8WfOk2hkaMsS0ZAsWzt', 'Atbai', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OJGHQh0Y76pDOAGYOUqT', 'Gebeit Maadin', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qjlqgZX2KOIagHBXZdrT', 'Port Sudan', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gCSWj5B3r04fc87j4oNT', 'Sawakin Town', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('YOZENtiDrK0cdLmAyCUj', 'Dordeib', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tIWGV8uMGO80hDsJzS4V', 'Gebeit', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ealWnAylWxDdysDOnTut', 'Haya', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bl7zUZJsEnc0ozF7AtaO', 'Mosamar', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vM40b1CKzrJLaYwZPrDZ', 'Sinkat', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gmGYZVrVn7Nkb2SM0IwL', 'Tokar Genoub', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TSTn77MYlx0sGWAoToKR', 'Tokar North', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aeidFQlK3aHIYhuoXDhl', 'Abu Hamad', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yAw6DqTFVLWWDcGFZOre', 'El Shereik', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('eCwjBpHlwxtpOR66ANyI', 'Sherri', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TTX6q9sEwO9o9aJK0bRB', 'Ez Zeidab', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('l7RK6kDPgQlJbI7MUKm7', 'El Matammah', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qKb5YOIMYsaEGukZag6j', 'Wad Hamed', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vRphiodTTdk1UdAMoHi5', 'Ed Damar', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Rw6Iz4SfwjySD6EsaCPJ', 'Sidon', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dXi3M7U4EmrhVF0Qb3lc', 'Barbar', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6XOCEWW28TzqxsNU4tIu', 'El Bauga', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WASuWiXSyhZRB3oIPChs', 'Shendi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cEtRJvARxC3SIIINNcTC', 'Eastern Dinder', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MsIOr19IXGtHYARclhcQ', 'Es Suki', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oityZJhbTYhZ4ZWbapvS', 'Karkoj', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7KrOBtvuvrPSUp1YRQck', 'Western Dinder', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('P2S2LFnZzVf76k1bS4Dl', 'Doba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('APVV5vyG70H9QuhxMrNy', 'Hamadna Allah', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8j41uFrPtWYhFsv8HTJV', 'Sennar Junction', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('JjlDuSGYQkPywrW01dgq', 'Sugar', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AIWNsMJna34LCWbVih8h', 'Wad Al Abbasi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sz3JO4MDohO4XyJrrDwB', 'Wad Taktok', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('s3LgWc9GhboSdlh9RBiB', 'Abu Hajar', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4dRaYYsovJSahvjcaV2U', 'Dali', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xFBFktEdgZV1DYomFJVM', 'Er Ramash', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0gIb6EVbS5sFnGICbceZ', 'Mazmum', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iBkfTwiJdutiDfvUFQiV', 'Umm Shuka', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fuBlAtGZi7tenVH1ZuwS', 'Wad El Neil', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VH5ym37r5DqQNRcXjURq', 'Buram', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uTscIM6Oyf1owbjoryUm', 'Er Radom', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5obcDIBHqHTS5i99PhSZ', 'Gereida', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('eHde9ME7sNKuml7cAacB', 'Idd El Ghanem', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0Jxn4dyqQGZCsYbOwO1r', 'Kiteila', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('naTA4LO3Qox1GCNhtVlu', 'Kubum', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BurTFY4w2A7onK5nSGpt', 'Reheid El Birdi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('M8R9wJb178jWNYE8mMsD', 'Kass', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('W6ET5OmgfAFFgmW8Tq3c', 'Nyalla North', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('42FJUB9eactyRzhfORzI', 'Nyalla South West', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('1QpQXRxRhytXGsAkprPr', 'Tulus', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4PYd2lazY1buA3GMhE8l', 'Abu Jubayhah', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('s8Wg3zlidcSUFj8WGwld', 'Debeibat', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('NxL4vBTSvUT3dzjwydDl', 'Dulami', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('A04egJTBBEefi64X736m', 'Habeila', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('S8S9s3jqcPq6lkhi2agM', 'Hamadi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6HPHuJxkJNV2DndlBLHi', 'Kurgul', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Wf1KopJOWfHdqObbwsXY', 'Salara', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OFHNHXb60iFWgBnreXTO', 'Heiban', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('NuG4Fiy1d1nHRniYynbP', 'Kadugli', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rWQ82J9D8fDAlRFW2fjV', 'Umm Durin', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BEYPJd0wlLb9aJG4TWSi', 'Abbasiya', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DaInaVvLjHdtst2uULyS', 'Rashad', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('CuGnZXvSkVN46syrjGYv', 'Talodi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('LvxnSBHDdXdkSBzdFXm8', 'El Geneina', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lG3UYsfTG9WgiwjGP0Vf', 'Silel Ah', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7w5wxvgdQCvlxsyL018m', 'Abyei', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('g37DHMu1r6TrmlFHUDqJ', 'Al Muglad', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8yOZgdXg07F4UQwUH46O', 'El Fula', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('A6bieDqNw5YyVfPQJDhA', 'Abu Zabad', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AOp72KSrsjPBgU1FwKnX', 'El Kheway', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('W3pRDu2Dfhq3vP4qKrXh', 'El Nuhud', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QkvG167xUytVJoF4sY5v', 'Wad Benda', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tnyVGB0lh8iWnZnWHqjF', 'Ghebeish', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('M8CEKX5s5cGARtAverbd', 'Odeiya', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3BIilnYebO6gN5ncAOnx', 'Soqa Ej Jamel', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2o5MshifkxGJdcjZjo1F', 'Legawa', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('k4KinpUxEJbemaapLt8e', 'Aid El Aud', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Isfd9y9PrO80qHbg7Tfk', 'El Arishcol', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9SjgU7Oz3WKVs1BJrt3P', 'El Halba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7sxDOGTHHSGhM1gcGWBE', 'El Kereida', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iR8XY6ij5Bf8bTAhJ3cT', 'El Wahda', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WJcStmFKBvexTDXLmG38', 'Ez Zireiqa', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('w6DTGDlA4CYQI5lwRXBR', 'Shegeiq', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HVhY2bpG2yI4kcAuKdPE', 'Umm Remta', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DZtJrxsVnF65rA3skgAG', 'El Kawa', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('JGBl5w0WMfjMT68DkqsZ', 'Es Shikh Es Sadeq', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('e12h7HImjFEJ99i2LNaz', 'Hashab', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iPoEJuhq3isLJHcMuezu', 'Na Eima', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MkoZJGIcSdChr2KFz3wP', 'Wad Jar En Nabi', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qSyfC5zICLKVQv5HYi7r', 'Abba Island', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('59WQrUOT9seNb8dpSGgS', 'Eg Gebelein', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('P9Pswy0Dgi7Is2xsgEno', 'Rabak', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3k8rEBEmuPlsZNKuY2K2', 'Abu Rukba', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zCM1CJRjvwkd3GuXrY9M', 'En Naeim', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('CejdmEWzp9Yt5jyZZrrg', 'Er Rawat', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AqtqysH3zMlCKruWOPEI', 'Ez Zeleit', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nIS7CbdQY1AJKPpVsGCj', 'Kosti Genoub', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HZG6Z57lUpcieXVZHNRt', 'Kosti Shmal', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XKw8qnYsfqp0PagdRj5B', 'Tendelti', 'sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7oL4ERlFy5uMyjIPaAev', 'Teite', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jbzDfkjfexEDVWeY5vUg', 'Warab', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rrTS9TpfjAv7jMzyJIvQ', 'Raga', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hcJh3r1mqFDHwKzJGUpM', 'Wau', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ssHbQZ7DLerAZ0090eQj', 'Eiba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('shd7f3Jhi2ut1q5j0Oov', 'Mareidi', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gBOevyOiDV3sSeXCJsr2', 'Mendry', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wNzL5BFVOCysYbmgIiIO', 'Ezura', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('NIqh4sUHvJJPHVgzc9aP', 'Tombura', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qD9Ov8cesb2S4W4JPI4X', 'Yambio', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('v2Ma3NAJpsu7AwI6JDBW', 'Central Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J7XlLJtDrpdq6xh9z94X', 'Eastern Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jZl8S5JHJvNdIwTJOKEY', 'Jungoli', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pYi3hTJYWcgQJru8BnaN', 'Lakes', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xcn2yPkcp750MMZNH5Kr', 'North Bahr-al-Ghazal', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Hiua10aB82T7zYhvryeh', 'Unity', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qw1VGk5hEah3qqLUtanz', 'Upper Nile', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9smOAf2rZnJNEM5zeiSx', 'Warap', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oFmWLW1OnXxCujbEzN13', 'West Bahr-al-Ghazal', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aXXgxnzeeqp37ZzDVROT', 'West Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kjjcQjpUmTwgl6TA9STU', 'Bahr al Jabal', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fY7IN4CfTsNvDtjv0rJ8', 'Kajo Kaii', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EhkHCvGJxMtHctX6q7KH', 'Nahr Yei', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('1TrmOwSnlk2wgMwwAzvL', 'Terkaka', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dK0RkoTk5zRAMuOXaYwa', 'Amatonge', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PfKJQ5XFXH7rqGXZ8Sew', 'Kapoeta', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('i4igQuyb9Dg1gaew1JC9', 'Magwi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kv37sIVoDnFn5ODumMHd', 'Shokodom', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DwaCPOlsDe26dklOoVcU', 'Akobo', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qKmk97t0BQrN54SFEt9o', 'Ayod', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hUSXx8jkELJN9ENoNCAT', 'Bor', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dOZcASTFGZnNppfT8UdP', 'Fam al Zaraf', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2P7ygNiJC44BsDTrPZys', 'Nahr Atiem', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('us2BK9YYdudc0FJeb6PR', 'Pibor', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J5xa2MeC23aLGhACqrSr', 'Wat', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vpocai9CN1QjimesP809', 'Aliab', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nwP3wwMFM8I6BS15uhwo', 'Rumbek', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('19ooffLj1tKtP8sI8CsL', 'Shobet', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('35mfdozC9fC166DIcMXi', 'Yerol', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('G8nasE86UrSgQELppIa1', 'Aryat', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ATPmTFNAyfqlfQONMvHQ', 'Aweil', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ht3CGUKgxJ8kHHM7CHKj', 'Nahr Lol', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Vz63wpKlfgz90gNOnYZf', 'Wanjuk', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jQIaJreGjMka2D8M9mQ0', 'Al Leiri', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('g0NNVqbAIBHZND4igRzV', 'Al Mayom', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9VLDOMhuFy7uYUOpX3JL', 'Faring', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vw6KlV4r8939RZv8ra0j', 'Rabkona', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('R6tJoXDxPMaOgi34x0QR', 'Al Mabien', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iqGRayxCNElLdNHgpX48', 'Al Renk', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oR1CsLUD4QeX24rpaoBN', 'Baleit', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WQej9EvL82shtcKJS375', 'Fashooda', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('YxEbipNo8q2CdTbOdcvG', 'Malut', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8bJFKrgr55NyoOEdl8mi', 'Mayot', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TeVYd2NqpA9lNwr7n44S', 'Sobat', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VxCn4lLxd5w245CMIDQq', 'Tonga', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kzNYhYGjWfA0lN6paxjp', 'Gogrial', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('i34AKx1wEmk9H4Fb80cb', 'Malek', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QsDTAiPeFo4JjrwFn5QQ', 'Tonj', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J4EyVTB9FlwYR1JkiZqk', 'Warab', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4jnR9CEWddKtbWP5oaaV', 'Raja', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mt3iUzNTexK3mHAW3Un6', 'Wau', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zy9oQnO5bIWihkHgX26T', 'Meridi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6iUqKLPX4n68GxQ1VEWS', 'Mundri', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fqsaG0UFSDvMprivtsuH', 'Tombura', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('y9JTJf0bBW2Yp3ngClfV', 'Yambio', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J2iuXWUkDHAbjspnUhwQ', 'Juba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O03JKmGJb7wpoUsBYfWf', 'Kajikaji', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EjfvkxBUnX7fkUAveQTx', 'Yei', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XGqtSssZuqMGQ0jyl7AO', 'Treikaka', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uIQhEB4OLf6ACXpo05Z4', 'Akotous', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Trhw2bHWdcsZLOLXc4td', 'Toreit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4stbyWzPljNrnFY0ngry', 'Kaboyta', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3NX9YFCjDrKWAkmrXATN', 'Magoy', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RpExVsXCHJjj3nKs62of', 'Shokodam', 'south_sudan', 'administrative_level_3', NULL);
