INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('south_sudan', 'South Sudan', NULL, NULL, 'https://w3id.org/okn/i/mint/South_Sudan');
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vA1oACvKWRn9Iy584eCW', '1060798250', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EZ9LuFfvnhYcE8wzUeIg', 'Kapoeta South', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sUYOv7mAVsVA1pLfVi90', 'Aweil West', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mXaAZdwl5Jm5toGGpkEl', 'Unknown_2', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5gPwP4VmlbibPdAfNqPI', 'Malakal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BBVkmStytDT1cYVsbJEQ', 'Lafon', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bGDatUIfQEiD17OHv9n7', 'Yambio', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Xv5S2gIdlGBJtYCGmtI5', '1060962950', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tKwxi8zcSp4OFXXq1KBN', '1060716270', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sdb9XjOJ4nFH0NYSH7my', 'Wanjak', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uyzjUzSIXcRNmkWGCR8k', 'Treikaka', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gX4JiYOovIMsVMybFzTG', '1060841230', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6YliWhRSdEt33RgYWuk9', 'Torit', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('epbtyNGX4INguPq1MFrF', '1060988630', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ViHqGPQK9OFmODsZtYPd', '1060809910', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HTv9jtk2dXEXQctm0kvt', '1060921730', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jAkm7qXhrA0umrIE9Uyv', 'Kajo-keji', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('B9XJEVrosXI20OPKJZyD', 'Leer', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aBHwo5hmveXJcNVCm4xZ', 'Rumbek Centre', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8rp1JsgVKF6PVABmkRm3', 'Rurali', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zwY9FPvxDoMOD37A9vtm', '1061001550', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qmMOF4D7BLeEKtxdRowk', '1061033490', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5nWACjbGJUlvtw8JNxjy', '1060823510', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('klAipBWtGI1DW8yZWckb', '1060840290', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zy7XE5eQ8XZBdrRyqRbH', 'El Leiri', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4B8t2kQU8BrFS1HUK1wj', 'Abiemnhom', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pDYHCXJu9ine8NBCgO7l', 'Western Bahr el Ghazal', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('K3c2hLcdPraIkjLCSdJ8', '1060810340', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6Mmnv67IvkCGnayBJOel', 'Ikotos', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2ObY6mEOde4x2v2VCDJ5', 'Mayendit', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qHGIAFPoQ7XB2IBOCjku', 'Bor South', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bXA5H3OqTkP6au8hBg2Q', 'Ulang', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ld0LzUN4OZH1BF0cmuVD', 'Mundri East', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RdeqIPE75hosDVpHD9ix', '1060869450', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fMjJP4PWJgguSoALXPEB', 'Panyijiar', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Fb6HzgTCw14JQakQGmuX', '1061053830', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yZGFE9tTjuyOseEsd2Sb', 'Koch', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vTXpTaXq3K8h466TO71h', '1060846100', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HQG002V5zssu6F8QMQqm', '1060820590', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lmL0DZrB9k7W1dhAaAYm', '1061041420', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cOQ56XfOC9L7XbHg29cX', 'Unknown_1', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0MFIFg1cu8t6LqYpJQQV', 'Malut', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2hm4WuFlhPzcQilGVNlb', 'Upper Nile', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HAgdil5p0cvSaHAwTieS', 'Gogrial West', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('K2bPLJap6ZLShwQXjC2o', 'Uror', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0fx745QkJMmVSjCyYs7x', '1061001800', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('d1Wmrv1Lf5E0uRu2aAN6', 'Eiba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('eNYx6HSa0AVDCO9qGh5I', 'Tombura', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hJ60usMx4splt3OPFit7', '1060856340', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dxQCUOewvUa35tdhjvOb', '1061022690', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Jylsy3KgXLwrgHw8YAyk', 'Eastern Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('12Ew48IsHiuWap7lCfCP', '1061051660', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2Gj0UeXAN3m56Wkx64i4', '1061033480', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('epi4iE1Q1BMmIWgraDjs', 'Malakal', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UyXg9vswy9xrXRgfoxq4', '1060848180', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SLPQEZDQ1M1V8uNNyQZM', 'Melut', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('btEGC6dII2rQXtwjMIKS', '1060856140', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qJ79fbqm87FXrj83lcnp', 'Mendry', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uEyTsnLLYIMmUBkkVwE6', 'Raga', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('r5Z6NkzH2kFmkNW1Dvf2', 'Rubkona', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5nMo11NChpchMBhteTaA', 'Unity', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('eCjPouBr2dttoo5OXz6k', '1060840470', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PqLqxEgk91ixPMDxrkRk', '1060989620', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5EXRWrCqzcpGEc73c8IC', 'Twic', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2yyFrLPrZ1okTBu74D63', 'Juba', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lSzmIaxBYiFY3g5tLs5M', 'Nzara', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OROsFg73dbiIkuOxkqTN', '1060728700', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('M9ts6KWqHkixUu82wrGi', 'Wat', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Ayc1W3pp62HCnr0SktaX', 'Gogiryal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('us8KY8WuCr4a1kwnsMWH', '1061041490', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PyYt3bQcTKJlvJHV1HFW', 'Pariang', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('m8QLgkJlezW2CQfJz4rJ', 'Bybor', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xuTQiHcwDBRN7O8ufZQG', '1061016250', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RwsrRLjzHMAjsM7ok12q', 'Toreit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('T2qQIAqOMSkFUes9N2fk', 'Wulu', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iiiqTqKm9dzenSfcMSro', '1061016240', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7EOGYV2CllN4rSBpbaP6', 'Teite', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OZohoeSxAHrqVktM6QbS', 'Yerol', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tTezBlY0LMqyBXUQizb2', '1060861680', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sOWCsfiiLeYEomZDSmcK', 'Gogrial East', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UNQEDlc1WG67xhi3ma8V', 'Maridi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('txnZl6plfr3yhdUmQNxM', 'Tambura', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('93vd7EaW6RCGDA9sVfKS', 'Pochalla', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SeqeTaWu3edcjaQYhtoZ', 'Juba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6NSZSmqHphLBrZBMw9HH', '1061055500', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OFfx9Q0m7OaPLEjz3uLU', 'Warrap', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xdnOVCHXmVUs75vo72ZJ', 'Abyei Region', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J8QA4tPMysOk0OM5RoLO', 'Ezo', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('IAFkJBldVnorBGlwGToF', 'Rumbek East', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('C59NBUEnrFx32m2Kkbkt', '1060843040', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('eKj9S2ekit26S0ZSALIU', 'Jonglei', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sOCOOfVZkO45fhH4sb8k', '1060824850', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QdhWKqoR7g8WpxLs8ZN1', 'Nagero', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0pBMy2lpHLw1ekkgBeQF', '1060854480', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Vk6FDRjTdXTTFCWsuqcT', 'Longochuk', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QLE9DPHsyeoeH7XxgX0k', 'Aweil', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6gDlr1UwojjVmiZB2vD3', 'Warab', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bQpwm7pRsnb1Ars85B4v', '1060913840', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0V0JIX9E2gSrsPXdHwnq', 'Kongur', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dBkxcOGtv0taHKt6Oxbu', 'Aweil Centre', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('JUo0KR1JQGf9NCdPf4Go', 'Aeiud', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KBlEFkzUvFuiDlDcGfxS', 'Wau', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hGoXGtHT0EtQwnOgZCjQ', '1061051360', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sUXGF0JD6EOYYG4yxPBr', 'Tonj South', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('IuVDmPQGAuKQ1pXf66Sy', '1060773760', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('miZ7QMoySYSgeOywGB61', '1061053930', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('N1U73gQ6i1swTPL6XVlh', 'Luakpiny/Nasir', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('JyqREhGKtwrK0KrmeWtM', '1060837870', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wVQha93RQBfioYEK6BsX', 'Yirol West', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vrRU97vw0m7znGEdi2P5', '1060827240', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jpgJedNarEUNevXwTqbL', '1060864590', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TXXY7wsoX2BROFdgb6FY', '1060883500', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6CBJnsY36WzZaExuQome', 'Mabein', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TbWcyIdERZnHmbOD9Nqn', 'Guit', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wf5p0tLJ2SC3rkiNXVy9', 'Odeth', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ujGSWuVMOIFPY50Ri1Xa', '1060999130', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WQ83h1D6U1xPChclJMuy', '1061051160', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wMow5vvEp4kbVP0t3tDP', 'Mayot', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XxqzpZ1aeTSj3qMYHQht', 'Central Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ru1dCe9PcgXJWhhvdqXt', 'Nyirol', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('a3pujpq0wN6b93JoED08', '1060872120', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('v48quFL6o0TTAsjwbgz6', '1060989610', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uWiZpAJ8CAtmmL5cc7De', 'Cueibet', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vRPsX40FCWunbbDchun7', '1060783650', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UHYhzPGGsO9rcZejdaUc', 'Kapoeta North', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('we9Lk3iTYl9nY2i84pzJ', '1061052940', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tJUnvEY1mlYw0mK3aIZr', '1060883230', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('YbfjcWSPqyAlLOthPjkC', 'Yei', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bzXg15Z85N0wiV2LIO2v', 'Mundri West', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XARblZFeCvvt023XVLuy', 'Tonj East', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('P1a3E9cNMssHKxWpRqUv', 'Yambio', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ob5HgEmlF1qZRbKnrPi3', '1061060260', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zxvhCOJrfB4RJwMELgS5', 'Akobo', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('i0fJw8L2xvOu5NGDT2sa', '1060949080', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vZLZQ5HZNSpbBkpPJ0L3', 'Renk', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('YWRW3qYmr1QazYDRxCru', '1060864580', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4xrY8lIcNvkJzzVTaMXS', 'Ezura', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2Velj7Hq3R230f5MOXU4', '1060852010', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('M3bHKnhKeJdAXNmSc2oo', '1061011930', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kKOzOFAezXFTkPqnMOvt', '1060909250', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('i8QTGlpkGTJzCw8dQlN2', '1060832440', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ocDDZaaV98mfU1xjDGda', 'Kapoeta East', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8C7AfsStw0QZZLtDIBtZ', '1060873210', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bRWUK5sMhuP5GXwu7Z2Y', '1060800160', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3m5aPZzsvJj1pSJGiCYc', '1060820900', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qDPceDe6LV4h7GKK63dF', '1061053990', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tLdf7WKabhytvVPRfDOf', 'Shokodam', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SScZOnPO0sXB2XJ1cgGt', '1060837890', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Pc1seBjtCl6FSVsx9OTj', '1061053880', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UFLSJWCIGZRYKrkFFRjs', '1061022540', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BbFEzDm6G4GaWhccjwiK', 'Mvolo', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('l7A7UkzPZaF4OSGmwDEG', 'Kaboyta', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WWBxmIbJX21QsCosrt2O', '1061020640', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('T8JWLfXU3X83L0BR2Bx5', '1060827490', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PtfmW5NK8lSy7zxnxSg8', '1060861870', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Y4PKLnNhHgGNEJranPyS', 'Baliet', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RoTq1b8R30d7EQspZYs6', '1061016870', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aR2f1bcUnvwEaGD9zC0Z', 'Kodok', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yechiXqfvZavZUbMzRFz', '1061033960', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('G1yklxgvxr1oEODIr8Ej', 'Oeiryal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('76FkPJA6OIckalkgAPCv', '1060962960', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EZVJZzC3pugjA9CvtxRh', 'Yirol East', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KugXhSXiXCdZhIlb7wOL', '1060913830', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WgYK6lAFd5hbjJWecw77', '1060851850', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('A1x8TqSX2AunlJZzkO61', 'Bashola', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VUpXXm5u5TiCAJ7y7oh4', '1060844660', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('T70guQobCxd1FrgSSI5r', '1060837630', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OL5xDY9hnXQqlHF98yrG', 'Maiwut', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5GL0lxL5ZeIwHxwUaMxw', '1060954500', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('CTbAE24Kp9O6vF0uQYDy', 'Geli Aliab', 'south_sudan', 'hydrology', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EXp4tyeL1NtDPxx1V94P', '1061017250', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KYnNiqDdQ4uFHURr1CXq', '1060841580', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ISJHho9XTeLkoNHvkbdo', 'Kajikaji', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TuIJb7IPVY3aagKH4Y6S', '1060728710', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7yhLBqptBOFzupMmuyKm', '1061012010', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('64NJCeypQ6zIHqKz4jlk', '1061024110', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VqmkoGr6RCODznsmQexH', 'El Meidom', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2uFgwKqDQU1saoHrc7Yh', 'Rumbek North', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2wYV3hT2fTJtQoKswU0Y', '1060885810', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ceVNl0L6JbJzqCiAzM3H', 'Mayom', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yHpYuUUbZA3ul5EfK4D1', '1060840450', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lMeC98SWpzpevMJ7LWi3', '1060840030', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cXYqoGa2U83TsGDGYJMq', 'Aweil North', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('m6y9xDRcUWsaQwiAY2tx', 'Awerial', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Lz3HH4dUKYWWFTAGheCq', '1060883520', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MxEYxHQfgOIwIe4Glnmu', '1060773750', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pSKjUTC2dscegBe5iNan', 'Pibor', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XKYfVv3c9xn66agKSxfQ', 'Lainya', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ovcR4C6E5ZzhczwT4OQN', 'Akoba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mW39s79c2ETyk40JL1MQ', '1060823900', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uXLiuX1OMJA8me17xbDL', 'Rank', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pgh8mPb2eAnE3a3Y0OSD', 'Fashoda', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rT6jSwEvS4bbyZ8Rv2ul', '1060832080', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('44XXtyhqNVi5y42Taz6W', 'Baleit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('e7Us6CudZ3LYfRq75WjU', '1060978570', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OnTtvV5EnEdgE0IHNzOF', 'Aweil East', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('URJvTxTub7daVuO8D86I', 'Bentiu', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aeMKj5NfAWDUdLBQReGt', '1060848400', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VsaCi97xUewMJCQr9H7c', 'Terekeka', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UG8hQRmKm6WlSQh74uD0', '1060883510', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gLD17GsF43EcQhs7WfCA', 'Panyikang', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ebPxrtR2BNZGrU4qvMFT', '1060716260', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2NtuFTu5AcX3pTrW2X0N', '1060798240', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hvkViluRGohKoY3FyOtL', 'Ayod', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0UXQGszEgUYoN7H49ju8', 'Morobo', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ISZIjb8w3ePedhssS4rZ', '1060869460', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tHf8gzhYdF4lJekgm78g', 'Raja', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('k0uvR3rfYrrZb8KgUPXp', '1060949070', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dkCDB4okflh0CBQmq6rd', '1060988620', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SpptdqQzlXfOvyuQjNuU', '1060800150', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yityVtE5mnTkLld1jjpg', 'Manyo', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BYhY1l89kNXf1Z8kOC8D', '1060999120', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2tjrNoUq0wT5M76OmN39', '1060872280', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qrCI1h8BklmToslpZIaQ', '1060965910', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('y755WqtPq7lZvSWC3Mos', 'Budi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('CXQDZyN5Ni07fGBs4DeC', '1060783860', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yEtR4myUrFgYyysNcjUz', 'Twic East', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Mh0br9iGJZZ36X6elROk', 'Lakes', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yPMbnqKQUIzoU2y92a5r', '1060837610', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('50sr6i3BtYg14bDa4IUI', 'Mareidi', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PDXLXzazKEtyA07TzrZP', '1060921740', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aDxlEnnYxvhL9TZWa4FP', 'Magwi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9xHnaEDbsGd19PWJJqE4', '1061017030', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4wu2Rhzhx2zZn6q4o731', '1060965920', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UnxEBXXRi9M7lfzmCZ5k', 'Magoy', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zcWyAuRdkRgWRlZnNn4h', '1060909260', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('phR4pvthLQuKxkYTF2zn', 'Aweil South', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ai3wavJv00rbv5SkTADq', '1060823290', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qdH4iMGGAmwNlLE1Mkmu', '1061024120', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TpWfUdyW8QMrUSdHGmVu', '1060841440', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('St0gRlls7oqNjAvW5uvz', 'Northern Bahr el Ghazal', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cA4T6P85xhNg1dUYptSa', 'Fangak', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('LLpZ8sv5JmkktMSaTxl6', '1060873200', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gRHUAGLLF0smdJQ1Yu8A', 'Fenjak', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bNNvAioppasfnTaInz7W', 'Naser', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ku9odnAcA6GfoEMmnZbb', 'Duk', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hxcsCiWPNoBbrXpZppRK', '1060841720', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WqL119dcLwQX5SfQB2hy', '1060843030', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('REngx3Ff3fMXJkCrB0yT', '1061029040', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('FASICYrHA4AHVUVoeHRd', 'Wau', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QLZJRxBegmkdL695oE14', 'Pongo', 'south_sudan', 'hydrology', 'https://w3id.org/okn/i/mint/Pongo_Basin_SS');
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('m6OLSwQqL6UWybdIwLJh', 'Ibba', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dhxrTkuIgVScXzjoLjQq', 'Yei', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('m4rXOaWanwpfDC22qeP7', 'Rumbeik', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lT5TVahbhwwRfLaZltPS', 'Tonj North', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MMb39GNyb0Iicx7IBnQW', 'Akotous', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DQGPXoGzfYehP3hCy3qu', 'Maban', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qDiN9TizoK75DnyVpALB', 'Bor', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3aw5tAZxUjSVIUzBJ7xB', 'Shaweit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lOBwfG5yEPi843WNRblL', 'Jur River', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iNNjSyXQXXmsQ58JuC9U', '1060823700', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cTTlLYBDF6vkaQfQcqL0', '1061051510', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EmdNhSylO8COCGAIuwpe', '1060844900', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('30mtlwe2oVf3qmsHf7jk', '1060845900', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KeOz1NmXGVtrkxNT0Boo', '1060978730', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rRtOPOWD5bDfrW3hpp7W', '1061017230', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WxVIfLuv67lmXtfytyb6', 'Western Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sx4nn7xJCSWViqWjKIDd', '1060954680', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UcVTklx0tj1dl7xRSfi2', '1060854290', 'south_sudan', 'agriculture', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yDp4FENBud0EJb185PF7', 'Canal/Pigi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rbWiLlYhRCMrdWBPmkBw', 'Kongur', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('S1T6Hpd7MF5nDWYPAmwn', 'Aeiud', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0Vogrk1MgfhUBDWYq4ot', 'Bor', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rmTQX5Q1PzLcQgfCcpjH', 'Fenjak', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lvbzPhyLNqvtpo6iIxXw', 'Akoba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rnmtpRHeutB5c9DiTf2J', 'Bashola', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pMRsrRDdQq5dB3AtjcDL', 'Bybor', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rytkl70BrIefcui8mFyu', 'Wat', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AbhuZk717pO69VO8IGPr', 'Oeiryal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4VRi5HcSqMD5P0DVTRMa', 'Rumbeik', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('lkrfUAnOGiVqou9TYaDS', 'Shaweit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('608tMEyme7OJF0boeD6X', 'Yerol', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5gfOMcv2NfsdSvdY3DCB', 'Odeth', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pFEP6aL4MdRsBqEMO0eM', 'Aweil', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O3Di032vRKA1oPvkBvVB', 'Rurali', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dcDi1Na7y4gJ2HeMJK8v', 'Wanjak', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9WS46liyDPlbeMzf6W68', 'El Leiri', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TkyYIHuY4khyH3MwRc4w', 'El Meidom', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bRgWe06yXSye2j1VJ1me', 'Unknown_1', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pzWKRBIrkPJ2GO1UlSmH', 'Bentiu', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Ts9IkD61KIuSA43FTTyf', 'Mabein', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OPRgx0o2JWFqKnSLO9lw', 'Rank', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O4QebFBFYvRyRIgB8b3m', 'Baleit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8YWeUFIOCrWj7HOtRLxC', 'Kodok', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OfGcncjZfHu0gtZdwWIw', 'Malut', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HAgcibttlG1pgSw3O0Z5', 'Mayot', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jqVzebwrtaPhPUi3gpAI', 'Naser', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bsBfFyQb1FsJDa3ot3Us', 'Malakal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Z46l3jh96RvFHadOfShc', 'Gogiryal', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7RnHqEdd2ythisAJsWqV', 'Unknown_2', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7oL4ERlFy5uMyjIPaAev', 'Teite', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jbzDfkjfexEDVWeY5vUg', 'Warab', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rrTS9TpfjAv7jMzyJIvQ', 'Raga', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hcJh3r1mqFDHwKzJGUpM', 'Wau', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ssHbQZ7DLerAZ0090eQj', 'Eiba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('shd7f3Jhi2ut1q5j0Oov', 'Mareidi', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('gBOevyOiDV3sSeXCJsr2', 'Mendry', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wNzL5BFVOCysYbmgIiIO', 'Ezura', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('NIqh4sUHvJJPHVgzc9aP', 'Tombura', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qD9Ov8cesb2S4W4JPI4X', 'Yambio', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('v2Ma3NAJpsu7AwI6JDBW', 'Central Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J7XlLJtDrpdq6xh9z94X', 'Eastern Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jZl8S5JHJvNdIwTJOKEY', 'Jungoli', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pYi3hTJYWcgQJru8BnaN', 'Lakes', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xcn2yPkcp750MMZNH5Kr', 'North Bahr-al-Ghazal', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Hiua10aB82T7zYhvryeh', 'Unity', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qw1VGk5hEah3qqLUtanz', 'Upper Nile', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9smOAf2rZnJNEM5zeiSx', 'Warap', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oFmWLW1OnXxCujbEzN13', 'West Bahr-al-Ghazal', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aXXgxnzeeqp37ZzDVROT', 'West Equatoria', 'south_sudan', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kjjcQjpUmTwgl6TA9STU', 'Bahr al Jabal', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fY7IN4CfTsNvDtjv0rJ8', 'Kajo Kaii', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EhkHCvGJxMtHctX6q7KH', 'Nahr Yei', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('1TrmOwSnlk2wgMwwAzvL', 'Terkaka', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dK0RkoTk5zRAMuOXaYwa', 'Amatonge', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PfKJQ5XFXH7rqGXZ8Sew', 'Kapoeta', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('i4igQuyb9Dg1gaew1JC9', 'Magwi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kv37sIVoDnFn5ODumMHd', 'Shokodom', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DwaCPOlsDe26dklOoVcU', 'Akobo', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qKmk97t0BQrN54SFEt9o', 'Ayod', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hUSXx8jkELJN9ENoNCAT', 'Bor', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dOZcASTFGZnNppfT8UdP', 'Fam al Zaraf', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2P7ygNiJC44BsDTrPZys', 'Nahr Atiem', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('us2BK9YYdudc0FJeb6PR', 'Pibor', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J5xa2MeC23aLGhACqrSr', 'Wat', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vpocai9CN1QjimesP809', 'Aliab', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nwP3wwMFM8I6BS15uhwo', 'Rumbek', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('19ooffLj1tKtP8sI8CsL', 'Shobet', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('35mfdozC9fC166DIcMXi', 'Yerol', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('G8nasE86UrSgQELppIa1', 'Aryat', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ATPmTFNAyfqlfQONMvHQ', 'Aweil', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ht3CGUKgxJ8kHHM7CHKj', 'Nahr Lol', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Vz63wpKlfgz90gNOnYZf', 'Wanjuk', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('jQIaJreGjMka2D8M9mQ0', 'Al Leiri', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('g0NNVqbAIBHZND4igRzV', 'Al Mayom', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9VLDOMhuFy7uYUOpX3JL', 'Faring', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vw6KlV4r8939RZv8ra0j', 'Rabkona', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('R6tJoXDxPMaOgi34x0QR', 'Al Mabien', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iqGRayxCNElLdNHgpX48', 'Al Renk', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oR1CsLUD4QeX24rpaoBN', 'Baleit', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WQej9EvL82shtcKJS375', 'Fashooda', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('YxEbipNo8q2CdTbOdcvG', 'Malut', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8bJFKrgr55NyoOEdl8mi', 'Mayot', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TeVYd2NqpA9lNwr7n44S', 'Sobat', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VxCn4lLxd5w245CMIDQq', 'Tonga', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kzNYhYGjWfA0lN6paxjp', 'Gogrial', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('i34AKx1wEmk9H4Fb80cb', 'Malek', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QsDTAiPeFo4JjrwFn5QQ', 'Tonj', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J4EyVTB9FlwYR1JkiZqk', 'Warab', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4jnR9CEWddKtbWP5oaaV', 'Raja', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mt3iUzNTexK3mHAW3Un6', 'Wau', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zy9oQnO5bIWihkHgX26T', 'Meridi', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6iUqKLPX4n68GxQ1VEWS', 'Mundri', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fqsaG0UFSDvMprivtsuH', 'Tombura', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('y9JTJf0bBW2Yp3ngClfV', 'Yambio', 'south_sudan', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('J2iuXWUkDHAbjspnUhwQ', 'Juba', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O03JKmGJb7wpoUsBYfWf', 'Kajikaji', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EjfvkxBUnX7fkUAveQTx', 'Yei', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('XGqtSssZuqMGQ0jyl7AO', 'Treikaka', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uIQhEB4OLf6ACXpo05Z4', 'Akotous', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Trhw2bHWdcsZLOLXc4td', 'Toreit', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4stbyWzPljNrnFY0ngry', 'Kaboyta', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3NX9YFCjDrKWAkmrXATN', 'Magoy', 'south_sudan', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RpExVsXCHJjj3nKs62of', 'Shokodam', 'south_sudan', 'administrative_level_3', NULL);
