INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('california', 'California', NULL, NULL, NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Ww6KH69bnSbOyf3PlB8u', 'Alameda', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DGhbP1dTTKdwD9mwfIZR', 'Alpine', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pS3YxNw85Shf3Ld39Rvq', 'Amador', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9spIlno1hwNOyN8819FQ', 'Butte', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RCEml2MyQWujrgHnY70x', 'Calaveras', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PzVESbWM6laYI9qFqeZJ', 'Colusa', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('pFohgRXEFVuSsx2PebDQ', 'Contra Costa', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('joPIkIVo4dF4WAFig6IZ', 'Del Norte', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MJe79g8VixvPeineSxyI', 'El Dorado', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('X55M2YdAxGd3XqxhjM8O', 'Fresno', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OTKAeYEam3PWhf54L2Lr', 'Glenn', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('emRBw1km9rwTflogJZmG', 'Humboldt', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3tngy4vY9EcxJBaj1R3l', 'Imperial', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nQghSwxWfF1kv7q2tYIw', 'Inyo', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vV11QNK6dyf0FiBWvmKC', 'Kern', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mbzMF9UznJ6PYEjBwEjt', 'Kings', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BXfaeVkV5Vkhmwp8cGK5', 'Lake', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xeakufzAMfKMDbgXSKoO', 'Lassen', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('heYfTMJf2pY8icfxM25N', 'Los Angeles', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('q2VC7LBXNc3Jd9hMiIgc', 'Madera', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BmvSc8Zc5WjnYc9s8nbE', 'Marin', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('x2Y2mDwc1lr59iFoUEyq', 'Mariposa', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('S3fLYetEKSR7PavYkCPd', 'Mendocino', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iJltG03fd5Bn2fLLZMcO', 'Merced', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('l0yKOqJacbg4Ufw5efDa', 'Modoc', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DFEaui9v7EihHbNwwsvg', 'Mono', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AUCqzkDCWisGsq2N18p8', 'Monterey', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('OTaLm8wiUpTzgTxaCHpJ', 'Napa', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QUtGoDuu4dAUPF0i8fdV', 'Nevada', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oXwGzogPZpLQpFQV3AtH', 'Orange', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bdTm8lLHK64KwGSwWnM5', 'Placer', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DS9LufBuyhDYrteJzIAL', 'Plumas', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fIzV6fj1bWEOrSuZFPSi', 'Riverside', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Jfl5BZ6Jpm0lHTcXTvoN', 'Sacramento', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('nIweRywq65FT4U4uExaL', 'San Benito', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dawyyZTeV21M5xoaLNOD', 'San Bernardino', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fMYZ3MgjWOgiFBm3FU1H', 'San Diego', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('2UfuwyxHZzwJ5RxsyVOB', 'San Francisco', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EpXVsOCKljSof4HpVHML', 'San Joaquin', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('sA4E9n7mQXeuUspUcOcY', 'San Luis Obispo', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Z17NL0Y60t6rm4JcZjsu', 'San Mateo', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zLe626pp9abqAP7xaBiw', 'Santa Barbara', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DTBcWPYaObi8q1waJNb2', 'Santa Clara', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('3gA9C5NW85gtaSc7d0om', 'Santa Cruz', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('4li8BqzWWiA7lsBpidbx', 'Shasta', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yuGTwtcBEId5mSX2Ecab', 'Sierra', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yTWTNSnlfwrqm3Nvsxhf', 'Siskiyou', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('yrjvcMXr3bjiJFVOE6uT', 'Solano', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aLStmtR10bw2Qjn5b2ud', 'Sonoma', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('QoZrv6nMGCwKv6uqUDGI', 'Stanislaus', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('waVjJtru5FNgyWj7fREa', 'Sutter', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Xwhmp1Xj2cQmHe6wyv4m', 'Tehama', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('DBAa12moaHwEfZUlMXYo', 'Trinity', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('H9MBmAOvfFsa4jQZ3UIp', 'Tulare', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5T3XPyv44BEv9wuP8Xvd', 'Tuolumne', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MwldAkaZ0p6STdNqi3ap', 'Ventura', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AggfmwqLgYDnYnjCCKic', 'Yolo', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xwuXEmMiTJmRpqvImmJd', 'Yuba', 'california', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aa6latmY0YEojrzdvGbm', 'PW-40', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Vfa8dc8ckuXtqNBMUJYJ', 'PW-28', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('W12wVkFJZvKGHcKgkaE6', 'PW-11', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7wKquR0z0qeyhcD1nZFI', 'PW-12', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vGXbp57QaRgBzNr9RdfA', 'PW-20', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('96tOx9EK3TIggW5tf6hi', 'PW-21', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('45pN6omTTlSVaSPIVgUJ', 'PW-33', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('1DBWtaOFaNjr6pSkjXz4', 'PW-32', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('FGzCFFqbZQOr3hHG327Q', 'PW-WA', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ABGzeD0JdUP0567vvKxZ', 'PW-39', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vq7x7kHUtNZ4cfcFqJz7', 'PW-37', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('GlmOMHKwLdGo0d3UjwXe', 'PW-38', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('oEe7EJRoyPzWz7bLdeXs', 'PW-01', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9u5B3MF04Ps93qgI6NiZ', 'PW-02', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('e6rWNDZGkisynVuoWhU4', 'PW-04', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vpC0KaB4jjcaiR3iyOnb', 'PW-03', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('VE4UpwIFbXvwIrNtWBP4', 'PW-41', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ehJv3EjXiVIERBQqIDiz', 'PW-05', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AdIuclAaj6R1laKseEj2', 'PW-07', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('EQYETJlaWBJwG2cmZOFJ', 'PW-06', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('IoM5roeEZnZcmoMrUyF2', 'PW-08', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('b40Pp6utio4t0hOJX4gs', 'PW-YV', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WUfg779Imds1uIrretvJ', 'PW-36', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('X1o72YQtpnvoQY0B5SuN', 'PW-09', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('RChxNxuK0Lz8ZHKRsYlo', 'PW-10', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Qlzh19jFdXaRw3EtFzPV', 'PW-35', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('IdhxgCYnpcxNhZ2lBZEL', 'PW-34', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('O1wVG5t09v4Xtid5HfQ7', 'PW-13', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iUvbmpi63SPAaFe5zyOJ', 'PW-14', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('m6585jezme6CRs4cL8RV', 'PW-15', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6yQMg8jPCwpuNN5LmBoh', 'PW-17', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('f5pCslDxyqWsaBDeT3z0', 'PW-18', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('KsV55KdVY5UM7nAHSEpk', 'PW-19', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('YNNVCPIEJKfdSdg7MA1g', 'PW-23', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('o3DOXdzbOu2GPL0S5NNT', 'PW-22', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qP4RHcLIqdzWjYOegKMn', 'PW-24', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('YezcN2TWaib4YOm6af23', 'PW-31', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ISBIrHW97NyKLV2wYeOf', 'PW-26', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MINL9R2ng3NUXDTUQODy', 'PW-25', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('smAQVFTQZ7OoLnz6a5Xw', 'PW-27', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cWItt1XD7KaNVMVrMgw5', 'PW-29', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('UPWZRXynPOYP7GjXp0l2', 'PW-MG', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('z83hvPjczIe21nC3Or9X', 'PW-30', 'california', 'administrative_level_3', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('B8VaO5R91CsznAoMWYI9', 'PW-16', 'california', 'administrative_level_3', NULL);
