INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('somalia', 'Somalia', NULL, NULL, 'https://w3id.org/okn/i/mint/Somalia');
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('vVvb2q29ldws44UiqAk4', 'Awdal', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('an2QceP8qac9qoTbKMgB', 'Bakool', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('LB6FdvqrwGM9OHCdFnFK', 'Banaadir', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('CFXpzbHXnmrl0I61HmmU', 'Bari', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('THOQ0cOwXrMwy2s5gGtc', 'Bay', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('iqQhXKw6gkMCYk1E27aU', 'Galguduud', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('NfZMLAj5Tszf5wc5D6we', 'Gedo', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9rMt0i5jg4I0Z56EbE1Q', 'Hiiraan', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('B15REsgFFNRJn8TtbrLd', 'Jubbada Dhexe', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uE11otfZutyKm3Myxjpb', 'Jubbada Hoose', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('qP94icgQTgBI6gsUYzP4', 'Mudug', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7wUoOUorLOMgAVwdjIlZ', 'Nugaal', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('FOzIxLP6t2Fx4i1vzdNQ', 'Sanaag', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9RzGdNYEs3ZBmWdj4Yjz', 'Shabeellaha Dhexe', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uXazgR8nnPiPFyq3Y7Zn', 'Shabeellaha Hoose', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('MOuOX7XLECDMt0xHiUTU', 'Sool', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('injlD7kw312AJWJ4oi4b', 'Togdheer', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('c2nQZvINuAFbhwKWGakp', 'Woqooyi Galbeed', 'somalia', 'administrative', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('khpYO1jGqIZbQaibw9jW', 'Baki', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('q3q7LTHrO3HXCRIjh4dS', 'Boorama', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fAIY6G372jZZIzZ6OEbT', 'Lughaya', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('BjLc4IqRpG7Moaf2Fu43', 'Zeylac', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('s91CgF9Z1ukVqvrj0Ihh', 'Ceel Barde', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('9D2wj1ThguuKVXudiJ5v', 'Rab Dhuure', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('aSm61LWC611bPUN2D02E', 'Tiyeeglow', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WXREFd0V5e2IoGKdx64u', 'Wajid', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('NUdjliwqn7utb7xRnZ76', 'Xudur', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('fhboC9bOTo7QVAX1E5kI', 'Mogadisho', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xMSKe1QYgsje2V92uosC', 'Bander-Beyla', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('5i4UrdzgjhkOj88aHEOi', 'Bosaaso', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ladoUQIL4lhgB9hrtNKZ', 'Calawla', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PmAolxA0Gmo3ECwjaBnw', 'Iskushuban', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('IBOY5YvEsEqKm6fQ2Xg2', 'Qandala', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('GJFNqBBGF1L4sSmqDPUr', 'Qardho', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('U6DWlen8hCxsw3tcLzdH', 'Baydhabo', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7ztD9bJu959HuT0DqyR6', 'Buur Xakaba', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('AkMxTPzAA84Irr2N6rBJ', 'Diinsoor', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hX1U6BHexIn4U4ykBozy', 'Qansax Dheere', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('kOXe7YBKzP0Bmgvt38ip', 'Caabudwaaq', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('q04SpXoqK5nhpyt6iXaY', 'Cadaado', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('CYtZp7dYgyaNaygNBGBa', 'Ceel Buur', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0E1C3QqE4VFetCrOGOzd', 'Ceel Dheer', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Xh9EuV6VVZodY7iP3W6f', 'Dhuusamareeb', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dFJKKdvxvXsKNMv7RlVR', 'Baar-Dheere', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('STaOVMM2JTZDRG2tRTwG', 'Beled Xaawo', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SguPMkHaA949QyHvv6dh', 'Ceel Waaq', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('twVFYxOjhjqbaerglwz6', 'Dolow', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('x4m38KWsiXNowGyj1uqJ', 'Garbahaaray', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('WSvf9TEXXQn9PO4erWNZ', 'Luuk', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HHNwuXRmPxEV5KKCBD5b', 'Beled Weyn', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('ApKh37B5hU7n2GW67JvY', 'Buulo Burdo', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Pz71gacOmCNSHYFzBrqP', 'Jalalaqsi', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('LUHQW3UQvZFHED20Txlw', 'Bu''aale', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rGEO7Xp8JpvdvLO0NTVe', 'Jilib', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('F826xoEKub3JqF59jM7s', 'Saakow', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('A17uEYMqFxaqzCsA0Gna', 'Afmadow', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8ktMvtH5b25wmZmiTR5p', 'Badhaadhe', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('7tAFrfngqV5czGm4u2k0', 'Jamaame', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('SivDkbwozV7t62OvzizM', 'Kismaayo', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('z1sTHMvJppHVJ6N0B7VL', 'Gaalkacayo', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('xGS73Q05H9fMTQ8kPLlj', 'Goldogob', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('hFCGFEgA3W0sEhIAwUqe', 'Hobyo', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zwO3saLiieDEsQ264nBh', 'Jariiban', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('TU5vSFkqJkGLIXiR2sih', 'Xarardheere', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('E1Hz1oJSTnGlNS1q2YGh', 'Burtinle', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('rVip8CLpw7p0ibBqxfjt', 'Eyl', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0ZEXQUW7tFtPc8UuJD1k', 'Garoowe', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('uMT6Ctx3eFefdYN2p9zm', 'Badhan', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('PMzojj5No0RFsBYBEKfr', 'Ceel-Afwein', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('mBWJPoKLzEFhBLiwCnGY', 'Ceerigaabo', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Y9afiKG0t4CQO7A1KGbg', 'Aadan', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('6YmK4vP8kd31IjpHAoJf', 'Balcad', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('8tzpxwX3ab3qQLFWpmHj', 'Cadale', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tUSZWIxgj7S0fhUo6KmN', 'Jawhar', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('l1sxyUXaz3QOmE9gQB7I', 'Afgooye', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('zFcIFQbg1iTcw0N7f5Pw', 'Baraawe', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('bRExSBrUzVnuvWyeuWA9', 'Kuntuwaaray', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Gtq0HEXFn2JAQggauxoP', 'Marka', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('68IWq0jxg21sb81quZxe', 'Qoryooley', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('acrT57vCgrGmlGCveqn1', 'Sablale', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('tDOiqcacg5rZzd8hcInm', 'Wanla Weyn', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('b0eB7AKyUeIym4zvi08r', 'Caynabo', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('cGPFFRnWlWY2za3mJHF9', 'Lascaanod', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Mio00tHuEmH7QjpHlJCp', 'Taleex', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('p6AHjzF4kyA6Zi8yZbQK', 'Xudun', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('dGiRK2KPQV43pZpYhDnU', 'Burao', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('HD8i7eyVw2AicWvEZ3VL', 'Buuhoodle', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('Pc0GQ68JrcRjllWSPTk4', 'Oodweyne', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('LTgaPG6RTukcenf1KCHK', 'Sheekh', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('wTXXLeMIaWpu1nuSJjrv', 'Berbera', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('0iqKFjEbrsefseTfw72c', 'Gabiley', 'somalia', 'administrative_level_2', NULL);
INSERT INTO public.region (id, name, parent_region_id, category_id, model_catalog_uri) VALUES ('D9moDHayFKlvRckdqWCI', 'Hargeysa', 'somalia', 'administrative_level_2', NULL);
